InterviewerPro/urls.py
from django.contrib import admin
from django.urls import path , include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    path("interviews/",include("interviews.urls")),
    path('users/',include("users.urls"))
] + debug_toolbar_urls()

app/urls.py
from django.urls import path 
from app import views

app_name = "pages"

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('payment/',views.payment,name="payment"),
    path('create_purchase/',views.create_purchase,name="create_purchase"),
]

interviews/urls.py
from django.contrib import admin
from django.urls import path , include
from interviews import views

app_name = "interviews"

urlpatterns = [
    path("",views.index,name="index"),
    path("new/",views.new, name="new" ),
    path("<id>",views.show,name="show"),
    path("<id>/edit",views.edit,name="edit"),
    path("<id>/delete",views.delete,name="delete"),
    path("<id>/comment",views.comment,name="comment"),
    path("<id>/favorite",views.favorite,name="favorite"),
]

users/urls.py
from django.urls import path 
from . import views

app_name = "users" 

urlpatterns = [
    path('',views.index,name="index"),
    path('sign_up/',views.sign_up,name="sign_up"),
    path('sign_in/',views.sign_in,name="sign_in"),
    path('login/',views.create_session,name="login"),
    path('logout/',views.delete_session,name="logout"),
]

templates/layouts/default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntervieWise</title>

    <link rel="stylesheet" href="{% static "assets/style/output.css" %}">
  
    <script src="{% static "assets/scripts/app.js" %}"></script>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <header>
        {% include "layouts/navbar.html" %}
        {% include "layouts/messages.html" %}
    </header>
    
  


    <main>
        {% block 'main'%}
        {% endblock %}
    </main>


    <footer>
        <a href="{% url 'pages:home' %}" >Home</a>
        <a href="{% url 'pages:about' %}" >About</a>
        {% include "layouts/footer.html" %}
    </footer>

</body>
</html>

templates/layouts/footer.html
<footer class="footer sm:footer-horizontal bg-base-300 text-base-content p-10">
    <nav>
      <h6 class="footer-title">Home</h6>
      <a href="{% url 'pages:home' %}" class="link link-hover">Go To Home</a>
      <a class="link link-hover">Design</a>
      <a class="link link-hover">Marketing</a>
      <a class="link link-hover">Advertisement</a>
    </nav>
    <nav>
      <h6 class="footer-title">Company</h6>
      <a class="link link-hover">About us</a>
      <a class="link link-hover">Contact</a>
      <a class="link link-hover">Jobs</a>
      <a class="link link-hover">Press kit</a>
    </nav>
    <nav>
      <h6 class="footer-title">Social</h6>
      <div class="grid grid-flow-col gap-4">
        <a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            class="fill-current">
            <path
              d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
          </svg>
        </a>
        <a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            class="fill-current">
            <path
              d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
          </svg>
        </a>
        <a>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            class="fill-current">
            <path
              d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
          </svg>
        </a>
      </div>
    </nav>
  </footer>

templates/layouts/messages.html
{% if messages %}
    {% for message in messages %}
        <template x-data="{ show:true}" x-if="show">
            
            <div role="alert" class="alert alert-{{message.tags}}">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span> {{ message }}</span>
                <button @click="show = false" class="btn">X </button>
            </div>
            
            
        </template>
    {% endfor %}    
{% endif %}

templates/layouts/navbar.html
<div class="navbar bg-base-100 shadow-sm">
    <div class="navbar-start">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
          <li><a>Item 1</a></li>
          <li>
            <a>Parent</a>
            <ul class="p-2">
              <li><a>Submenu 1</a></li>
              <li><a>Submenu 2</a></li>
            </ul>
          </li>
          <li><a>Item 3</a></li>
        </ul>
      </div>
      <a href=" {% url 'pages:home' %} "class="btn btn-ghost text-xl">InterVieWise</a>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1 text-xl">
        <li><a href="{% url 'interviews:index'%}">面試列表</a></li>
        <li>
          <details>
            <summary>下拉選單</summary>
            <ul class="p-2">
              <li><a>Submenu 1</a></li>
              <li><a>Submenu 2</a></li>
            </ul>
          </details>
        </li>
        <li><a href="{% url 'interviews:new'%}">新增面試</a></li>
      </ul>
    </div>
    <div class="navbar-end gap-2">

      {% if user.is_authenticated %}  
        <form action="{% url 'users:logout' %}" method="POST">
          {% csrf_token %}
          <button class="btn">登出</button>
        </form>

      {% else%}

        <a  href="{% url 'users:sign_in' %}" class="btn">登入</a>
        <a href="{% url 'users:sign_up' %}" class="btn">註冊</a>

      {% endif %}
    </div>
    
  </div>