InterviewerPro/urls.py
from django.contrib import admin
from django.urls import path , include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    path("interviews/",include("interviews.urls")),
    path('users/',include("users.urls"))
] + debug_toolbar_urls()

app/urls.py
from django.urls import path 
from app import views

app_name = "pages"

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('payment/',views.payment,name="payment"),
    path('create_purchase/',views.create_purchase,name="create_purchase"),
]

users/urls.py
from django.urls import path 
from . import views

app_name = "users" 

urlpatterns = [
    path('',views.index,name="index"),
    path('sign_up/',views.sign_up,name="sign_up"),
    path('sign_in/',views.sign_in,name="sign_in"),
    path('login/',views.create_session,name="login"),
    path('logout/',views.delete_session,name="logout"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'email',
            'first_name',
            'last_name',
        ]

users/views.py
from django.shortcuts import render,redirect
from .forms import  UserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def sign_up(request):
    form = UserCreationForm
    return render(
        request,
        'users/sign_up.html',
        {"form":form}
        )

def index(request):
    if request.POST:
        form = UserCreationForm(request.POST)
        form.save()

        return redirect("pages:home")
    
def sign_in(request):
    next = request.GET.get("next",reverse("pages:home"))
    return render(
        request,
        'users/sign_in.html',
        {"next":next}
        )

def create_session(request):  # 登入session
    if request.POST :
        username = request.POST.get('username')
        password = request.POST.get('password')
        # username = request.POST['username']
        # password = request.POST['password']

        user = authenticate(username=username,password=password)
        if user is not None: 
            login(request,user)
            next =  request.POST.get("next",reverse("pages:home"))
            messages.success(request,"登入成功")  # flash messages
            return redirect(next)
        else: 
            return redirect("users:sign_in")

@require_POST        
def delete_session(request):
    logout(request)
    messages.success(request,"已登出")
    return redirect("pages:home")

users/templates/users/sign_in.html
{%  extends "layouts/default.html" %}

{% block 'main' %}
<h1>登入</h1>
<h1>登入帳號</h1>
<form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}

    <input type="hidden" name="next" value="{{ next }}">

    <div>
        <div>
            <label for="username">帳號：</label>
            <input type="text" name="username">
        </div>

        <div>
            <label for="password">密碼：</label>
            <input type="password" name="password">
        </div>
    </div>


    <button class="btn btn-neutral">登入</button>
</form>

{% endblock  %}

users/templates/users/sign_up.html
{%  extends "layouts/default.html" %}

{% block 'main' %}

<h1>註冊帳號</h1>
<form action="{% url 'users:index' %}" method="POST">
    {% csrf_token %}
    {% comment %} {{ form }} {% endcomment %}

    {% for field in form %}
    <div>
        <div class="font-bold">{{ field.label_tag}}
        {{ field }}</div>
    </div>
    {% endfor %}

    <button class="btn btn-neutral">註冊</button>
</form>

{% endblock  %}