InterviewerPro/urls.py
from django.contrib import admin
from django.urls import path , include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    path("interviews/",include("interviews.urls")),
    path('users/',include("users.urls"))
] + debug_toolbar_urls()

app/urls.py
from django.urls import path 
from app import views

app_name = "pages"

urlpatterns = [
    path('',views.home,name="home"),
    path('about/',views.about,name="about"),
    path('payment/',views.payment,name="payment"),
    path('create_purchase/',views.create_purchase,name="create_purchase"),
]

interviews/urls.py
from django.contrib import admin
from django.urls import path , include
from interviews import views

app_name = "interviews"

urlpatterns = [
    path("",views.index,name="index"),
    path("new/",views.new, name="new" ),
    path("<id>",views.show,name="show"),
    path("<id>/edit",views.edit,name="edit"),
    path("<id>/delete",views.delete,name="delete"),
    path("<id>/comment",views.comment,name="comment"),
    path("<id>/favorite",views.favorite,name="favorite"),
]

interviews/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Interview(models.Model):   # 新增一個類別 Interview  ， 繼承了 models.Model 這個類別
    company_name =  models.CharField(max_length=100,null=False)  # 預設值 就是null=False
    position =  models.CharField(max_length=50)
    interview_date = models.DateField(null=True)  #null = True 代表：  這個非必填
    review = models.TextField()
    rating = models.PositiveSmallIntegerField(default=5)
    result = models.CharField(max_length=50,null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    favorited_by = models.ManyToManyField(User,through="FavoriteInterview",related_name="favorited_interviews")
    #                                                   # FavoriteInterview  這個時候還沒出現，會出錯，所以要用字串方式呈現

class Comment(models.Model):
    content = models.TextField()
    interview = models.ForeignKey(Interview,on_delete=models.SET_NULL , null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
# interviews
#     company_name
#     positon
#     interview_date
#     review
#     rating


# Join Table 
class FavoriteInterview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    interview = models.ForeignKey(Interview,on_delete=models.CASCADE)

interviews/views.py
from django.shortcuts import render , HttpResponse , redirect , get_object_or_404
from .models import Interview ,Comment,FavoriteInterview
from .form import InterviewForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages

# Create your views here.
def index(request):
    if request.POST :   # 如果送過來的request 是 POST  
        form = InterviewForm(request.POST)
        interview = form.save(commit=False)
        interview.user = request.user
        interview.save()
        # # 收集、新增資料：
        # # 收集資料  （從表單傳送過來的 POST 資料中取得每個欄位的值）
        # company_name = request.POST["company_name"]   #company_name(變數名稱) = 帶入 POST 請求帶進來的 company_name （HTML 中的<input name="company_name"> ）這個 的 value
        # position = request.POST["position"]         
        # interview_date = request.POST["interview_date"]
        # review = request.POST["review"]
        # result = request.POST["result"]
        # rating = request.POST["rating"]
        
        # # 新增 
        # interview = Interview.objects.create(   # 針對 Interview 這個 Model（在model.py的建立的） ，使用 Django 的Object中的create功能 新增這筆資料到資料庫
        #     company_name = company_name,    #  model 中的 欄位名稱   =  （收集進來的變數名稱）上面收集資料使用的 變數名稱
        #     position = position,
        #     interview_date =interview_date,
        #     review = review,
        #     result = result,
        #     rating = rating

        # )

        # return redirect("/interviews")
        # return redirect("interviews:index")
        return redirect("interviews:show",interview.id) 

    else:
        interviews = Interview.objects.order_by("-id")
        return render(
            request,
            "interviews/index.html",
            {"interviews":interviews},
        )

@login_required
def new(request):
    form = InterviewForm    # 新增一個變數 form
    return render(
        request,
        "interviews/new.html",
        {"form":form},
        )

@login_required
def show(request,id):
    interview = get_object_or_404(Interview,pk=id) 
    if request.POST : 
        form = InterviewForm(request.POST,instance=interview)
        form.save()
        return  redirect("interviews:show",interview.id) 

   # if request.POST :       #（舊版本） 
        company_name = request.POST["company_name"]   
        position = request.POST["position"]         
        interview_date = request.POST["interview_date"]
        review = request.POST["review"]
        result = request.POST["result"]
        rating = request.POST["rating"]

        interview = get_object_or_404(Interview,pk=id)  # 把 這筆 interview 挑出來，然後：

        interview.company_name = company_name 
        interview.position = position
        interview.interview_date =interview_date
        interview.review = review
        interview.result = result
        interview.rating = rating

        #更新
        interview.save()
        return  redirect("interviews:show",interview.id) 


    else:
        # interview = Interview.objects.get(pk=id)  #  pk =  primary key 主鍵  # 這個沒有引號的interview 可以改名字 interview_info 什麼都可以
        # interview = get_object_or_404(Interview,pk=id) 這樣也可以  ，可以直接搬到外面
        #comments = Comment.objects.filter(interview=interview)  #(interview_id=id)也可以
        comments = interview.comment_set.prefetch_related('user').order_by("-id")
        return render(
            request,
            "interviews/show.html",
            {"interview":interview,"comments":comments}
            )

@login_required
def edit(request,id):
    interview = get_object_or_404(Interview,pk=id)
    form = InterviewForm(instance=interview)
    return render(
        request,
        "interviews/edit.html",
        {"interview":interview,
         "form":form,
        },
    )

@login_required
def delete(request,id):
    interview = get_object_or_404(Interview,pk=id)
    interview.delete()

    return redirect("interviews:index")

@require_POST
@login_required
def comment(request,id):
    interview = get_object_or_404(Interview,pk=id)

    # Comment.objects.create(
    #     content = request.POST["content"],
    #     interview_id = id,
    # )

    interview.comment_set.create(
        content=request.POST["content"],
        user=request.user,)   ## 新增comment 

  
    return redirect('interviews:show',interview.id)


# @require_POST
# @login_required
# def favorite(request,id):
#     interview = get_object_or_404(Interview,pk=id)
#     user = request.user
#     f = FavoriteInterview.objects.filter(user=user,interview=interview)

#     if f:
#         f.delete()
#     else:
            
#         FavoriteInterview.objects.create(user=user,interview=interview)

#     return redirect('interviews:show',interview.id)

@require_POST
@login_required
def favorite(request,id):
    interview = get_object_or_404(Interview,pk=id)
    favorite = request.user.favorited_interviews
    

    if favorite.filter(pk=interview.pk).exists():
        favorite.remove(interview)
    else:
        favorite.add(interview)

    return render(request,
                  'interviews/favorite.html',
                  {
                    'user': request.user , 
                   'interview':interview
                   },
                   )
    # return redirect('interviews:show',interview.id)

interviews/templates/interviews/edit.html
{%  extends "layouts/default.html" %}

{% block 'main' %}

<legend class="fieldset-legend">
<h1>編輯:  {{ interview.company_name}}</h1>
</legend>
<form action="{% url 'interviews:show' interview.id %}" method="post" class="m-3">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <label class="label"> 
                {{ field.label_tag }}
            </label>
            {{ field }}
            {{ field.help_text}}
        </div>
    {% endfor %}



    {% comment %} action = 路徑   //   method =  get / post {% endcomment %}

    {% comment %} <input type="hidden" value="{{  csrf_token }}" /> {% endcomment %}

    
{% comment %}       舊版本
    <div>
        <label for="company_name"> 公司名稱</label>
        <input name="company_name" value="{{ interview.company_name}}" type="text" id="company_name">
    </div>
    
    <div>
        <label for="position"> 職稱</label>
        <input name="position" value="{{ interview.position}}" type="text" id="position">
    </div>

    <div>
        <label for="interview_date"> 面試日期</label>
        <input name="interview_date" value="{{ interview.interview_date|date:'Y-m-d' }}" type="date" id="interview_date">
    </div>

    <div>
        <label for="review"> 心得</label>
        <textarea name="review" id="review">{{ interview.review}} </textarea>
    </div>

    <div>
        <label for="result"> 面試結果</label>
        <input name="result" value="{{ interview.result }}" type="text" id="result">
    </div>

    <div>
        <label for="rating"> 評分</label>
        <input name="rating" value="{{ interview.rating}}" type="number" id="rating">
    </div> {% endcomment %}

    <input type="submit" value="確認編輯" class="btn btn-neutral">

    
</form>
<div class="m-2">
    <a href="{% url 'interviews:show' interview.id %}" class="btn btn-neutral">放棄編輯</a>
    <a href="{% url 'interviews:index' %}" class="btn btn-neutral">放棄編輯，回到列表</a>    
</div>
{% endblock  %}

interviews/templates/interviews/favorite.html
{% comment %} 
<section>
    <form action="{% url 'interviews:favorite' interview.id %}" method="POST">
        {% csrf_token %}

        {% if user in interview.favorited_by.all %}
            <button class="btn   btn-neutral flex items-center gap-2">
                <div>已按讚</div>
            </button>
        {% else %}

            <button class="btn  btn-ghost flex items-center gap-2">
                <span>按讚</span>

            </button>
        {% endif %}
    </form>
</section> {% endcomment %}


{% if user in interview.favorited_by.all %}
    <button  hx-post='{% url 'interviews:favorite' interview.id %}' hx-swap="outerHTML" class="btn   btn-neutral flex items-center gap-2">
        <div>已按讚</div>
    </button>
{% else %}

    <button hx-post='{% url 'interviews:favorite' interview.id %}' hx-swap="outerHTML" class="btn  btn-ghost flex items-center gap-2">
        <span>按讚</span>
        {% comment %} <svg class="size-[1.5em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor">
            <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"></path>
        </g>
        </svg> {% endcomment %}
    </button>
{% endif %}

interviews/templates/interviews/index.html
{%  extends "layouts/default.html" %}

{% block 'main' %}

<h1>面試列表
</h1>

<a href="/interviews/new/">
  <button class="btn btn-neutral">HardCore新增面試</button>  
</a>

<br><br>

<a href="{% url 'interviews:new' %}">
  <button class="btn btn-neutral">新增面試</button>  

</a>


<br><br><br><br>

{% comment %} {{ interviews }} {% endcomment %}

<br><br><br><br>

{% comment %} 
<ul>
    {%  for interview in interviews %}
        <li>
                                                                <!-- <a href="/interviews/{{interview.id}}"> --> 
            <a href="{% url 'interviews:show' interview.id %}">  <!--  這種寫法比較建議 --> 
                <section>
                    <h2>{{ interview.company_name}}</h2>
                    <h3>{{ interview.position}}</h3>
                    <h5>{{  interview.rating}}  /  10</h5>
                </section>
            </a>
        </li>
    {% endfor %}
</ul>
 {% endcomment %}

<ul class="list bg-base-100 rounded-box shadow-md ">
  
    <li class="p-4 pb-2 text-xl opacity-80 tracking-wide bg-blue-100">Interview List</li>
    {%  for interview in interviews %}
    <li class="list-row">
      <div></div>
      <a href="{% url 'interviews:show' interview.id %}">
        <div>
          <div>公司：{{ interview.company_name}}</div>
          <div class="text-xs uppercase font-semibold opacity-60">職稱：{{ interview.position}}</div>
        </div>
      </a>

      <button class="btn btn-square btn-ghost">
        <svg class="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"></path></g></svg>
      </button>
    </li>
    {% endfor %}
    

    
  </ul>

{% endblock  %}

interviews/templates/interviews/new.html
{%  extends "layouts/default.html" %}

{% block 'main' %}

<legend class="fieldset-legend ">
<h1 class="text-5xl">新增面試</h1>
</legend>

<a href="{% url 'interviews:index' %}" class="btn"> 回面試列表 </a>

<form action=" {% url 'interviews:index' %} " method="post" class="m-3">  {% comment %}  # action 丟到哪裡 ， 對應的 views 就要有def 來接{% endcomment %}
    {% csrf_token %}

    <div>
        {% comment %} action = 路徑   //   method =  get / post {% endcomment %}

        {% comment %} <input type="hidden" value="{{  csrf_token }}" /> {% endcomment %}
    </div>


    {% for field in form %}
    <div>
        <label class="label"> 
            {{ field.label_tag }}
        </label>
        {{ field }}
        {{ field.help_text}}
    </div>
    {% endfor %}



    {% comment %} <div>
        <label for="company_name"> 公司名稱</label>
        <input name="company_name" type="text" id="company_name">
    </div>
    
    <div>
        <label for="position"> 職稱</label>
        <input name="position" type="text" id="position">
    </div>

    <div>
        <label for="interview_date"> 面試日期</label>
        <input name="interview_date" type="date" id="interview_date">
    </div>

    <div>
        <label for="review"> 心得</label>
        <textarea name="review" id="review"> </textarea>
    </div>

    <div>
        <label for="result"> 面試結果</label>
        <input name="result" type="text" id="result">
    </div>

    <div>
        <label for="rating"> 評分</label>
        <input name="rating" type="number" id="rating">
    </div> {% endcomment %}

    <input type="submit" value="新增" class="btn btn-neutral">
</form>

{% endblock  %}

interviews/templates/interviews/show.html
{%  extends "layouts/default.html" %}

{% block 'main' %}


<h1>面試資料 {{   interview.id  }}</h1>
<a href="{% url 'interviews:index' %}"> 回面試列表 </a>
    {% include "interviews/favorite.html" with user=user interview=interview %}

    <h1>面試公司：{{ interview.company_name}}</h1>
    <h2>面試職位：{{ interview.position}}</h2>
    <h3>面試評價：{{  interview.rating}}  /  10</h3>
    <h4>面試心得：{{ interview.review }} </h4>
</section>

<a href="{% url 'interviews:edit' interview.id %}" class="btn btn-neutral mx-3 my-3">編輯</a>
{% comment %} <a href="{% url '' interview.id %}">刪除</a>   這樣不行！ {% endcomment %}

<form action="{% url 'interviews:delete' interview.id %}" method="post" onsubmit="return confirm('是否確認刪除?')">
    {% csrf_token %}
    <button class="btn btn-neutral mx-3 my-3">刪除</button>
</form>



<hr />
<h2>留言：</h2>

<ul class="card-body">
    {% for comment in comments  %}
    <li class="card-title">
        <div>                                   {% comment %} 用 Django的filter ：新增留言內容 換行 {% endcomment %}
            <h5> {{ comment.user }}    : {{ comment.content|linebreaks }}   </h5>
            <p> 留言時間：  {{ comment.created_at }}   </p>  
        </div>
    </li>
    {% endfor %}


</ul>


<form action="{% url 'interviews:comment' interview.id %}" method="POST">
    {% csrf_token %}
    <textarea name="content" id=""></textarea>
    <div>
        <input type="submit" value="新增留言到 {{ interview.company_name }} " class="btn btn-neutral">
    </div>

</form>

{% endblock  %}











<form action="{% url 'interviews:comment' interviews.id %}" method="POST">
    {% csrf_token %}
    <textarea name="content" id=""></textarea>
    <button>新增留言</button>

</form>